# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  port: 3306
  host: localhost
  username: root
  password: root
  database: sales

  #socket: /Applications/MAMP/tmp/mysql/mysql.sock
  socket: /var/run/mysqld/mysqld.sock

  variables:
   sql_mode: TRADITIONAL

development:
  <<: *default

test:
  <<: *default  